export async function fetchSuggestions(query: string) {
  const res = await fetch(`https://photon.komoot.io/api/?q=${query}`);
  const data = await res.json();

  // const data = {
  //   type: "FeatureCollection",
  //   features: [
  //     {
  //       type: "Feature",
  //       properties: {
  //         osm_type: "R",
  //         osm_id: 122604,
  //         osm_key: "place",
  //         osm_value: "city",
  //         type: "city",
  //         name: "Chicago",
  //         county: "Cook County",
  //         state: "Illinois",
  //         country: "United States",
  //         countrycode: "US",
  //         extent: [-87.9400876, 42.0230529, -87.5241243, 41.644531],
  //       },
  //       geometry: {
  //         type: "Point",
  //         coordinates: [-87.6244212, 41.8755616],
  //       },
  //     },
  //     {
  //       type: "Feature",
  //       properties: {
  //         osm_type: "N",
  //         osm_id: 5349571275,
  //         osm_key: "railway",
  //         osm_value: "station",
  //         type: "house",
  //         housenumber: "300",
  //         name: "Chicago",
  //         street: "West Chicago Avenue",
  //         locality: "River North",
  //         district: "Near North Side",
  //         city: "Chicago",
  //         county: "Cook County",
  //         state: "Illinois",
  //         country: "United States",
  //         postcode: "60654",
  //         countrycode: "US",
  //       },
  //       geometry: {
  //         type: "Point",
  //         coordinates: [-87.6356943, 41.8958413],
  //       },
  //     },
  //     {
  //       type: "Feature",
  //       properties: {
  //         osm_type: "N",
  //         osm_id: 1894033187,
  //         osm_key: "railway",
  //         osm_value: "station",
  //         type: "house",
  //         housenumber: "800",
  //         name: "Chicago",
  //         street: "North State Street",
  //         locality: "Gold Coast",
  //         district: "Near North Side",
  //         city: "Chicago",
  //         county: "Cook County",
  //         state: "Illinois",
  //         country: "United States",
  //         postcode: "60654",
  //         countrycode: "US",
  //       },
  //       geometry: {
  //         type: "Point",
  //         coordinates: [-87.6281877, 41.8966356],
  //       },
  //     },
  //     {
  //       type: "Feature",
  //       properties: {
  //         osm_type: "N",
  //         osm_id: 736035818,
  //         osm_key: "railway",
  //         osm_value: "station",
  //         type: "house",
  //         housenumber: "800",
  //         name: "Chicago",
  //         street: "North Milwaukee Avenue",
  //         locality: "River West",
  //         district: "West Town",
  //         city: "Chicago",
  //         county: "Cook County",
  //         state: "Illinois",
  //         country: "United States",
  //         postcode: "60642",
  //         countrycode: "US",
  //       },
  //       geometry: {
  //         type: "Point",
  //         coordinates: [-87.6553278, 41.8962116],
  //       },
  //     },
  //     {
  //       type: "Feature",
  //       properties: {
  //         osm_type: "R",
  //         osm_id: 21068694,
  //         osm_key: "boundary",
  //         osm_value: "statistical",
  //         type: "other",
  //         name: "Chicago metropolitan area",
  //         state: "Illinois",
  //         country: "United States",
  //         countrycode: "US",
  //         extent: [-88.9420709, 42.4957307, -86.929321, 40.7364954],
  //       },
  //       geometry: {
  //         type: "Point",
  //         coordinates: [-87.7666653, 41.6117047],
  //       },
  //     },
  //     {
  //       type: "Feature",
  //       properties: {
  //         osm_type: "R",
  //         osm_id: 126339,
  //         osm_key: "place",
  //         osm_value: "town",
  //         type: "city",
  //         name: "Chicago Heights",
  //         county: "Cook County",
  //         state: "Illinois",
  //         country: "United States",
  //         postcode: "60411",
  //         countrycode: "US",
  //         extent: [-87.674425, 41.543357, -87.59686, 41.48141],
  //       },
  //       geometry: {
  //         type: "Point",
  //         coordinates: [-87.6357079, 41.5062834],
  //       },
  //     },
  //     {
  //       type: "Feature",
  //       properties: {
  //         osm_type: "W",
  //         osm_id: 37126546,
  //         osm_key: "amenity",
  //         osm_value: "bus_station",
  //         type: "house",
  //         housenumber: "630",
  //         name: "Chicago Greyhound Terminal",
  //         street: "West Harrison Street",
  //         locality: "Greektown",
  //         district: "Near West Side",
  //         city: "Chicago",
  //         county: "Cook County",
  //         state: "Illinois",
  //         country: "United States",
  //         postcode: "60607",
  //         countrycode: "US",
  //         extent: [-87.6435652, 41.87521, -87.6427836, 41.8744684],
  //       },
  //       geometry: {
  //         type: "Point",
  //         coordinates: [-87.6431756, 41.8748689],
  //       },
  //     },
  //     {
  //       type: "Feature",
  //       properties: {
  //         osm_type: "N",
  //         osm_id: 10155717499,
  //         osm_key: "historic",
  //         osm_value: "memorial",
  //         type: "house",
  //         name: "Chicago Stadium",
  //         street: "West Madison Street",
  //         locality: "West Haven",
  //         district: "Near West Side",
  //         city: "West Chicago Township",
  //         county: "Cook County",
  //         state: "Illinois",
  //         country: "United States",
  //         postcode: "60612",
  //         countrycode: "US",
  //       },
  //       geometry: {
  //         type: "Point",
  //         coordinates: [-87.6742028, 41.8814716],
  //       },
  //     },
  //     {
  //       type: "Feature",
  //       properties: {
  //         osm_type: "R",
  //         osm_id: 123144,
  //         osm_key: "place",
  //         osm_value: "town",
  //         type: "city",
  //         name: "Chicago Ridge",
  //         county: "Cook County",
  //         state: "Illinois",
  //         country: "United States",
  //         postcode: "60415",
  //         countrycode: "US",
  //         extent: [-87.798492, 41.7205434, -87.759223, 41.690395],
  //       },
  //       geometry: {
  //         type: "Point",
  //         coordinates: [-87.7792196, 41.7014217],
  //       },
  //     },
  //     {
  //       type: "Feature",
  //       properties: {
  //         osm_type: "R",
  //         osm_id: 17581411,
  //         osm_key: "building",
  //         osm_value: "train_station",
  //         type: "house",
  //         housenumber: "225",
  //         name: "Chicago Union Station",
  //         street: "South Canal Street",
  //         locality: "West Loop Gate",
  //         district: "Near West Side",
  //         city: "Chicago",
  //         county: "Cook County",
  //         state: "Illinois",
  //         country: "United States",
  //         postcode: "60606",
  //         countrycode: "US",
  //         extent: [-87.6398511, 41.8790629, -87.6385412, 41.8783303],
  //       },
  //       geometry: {
  //         type: "Point",
  //         coordinates: [-87.6392607, 41.8786908],
  //       },
  //     },
  //     {
  //       type: "Feature",
  //       properties: {
  //         osm_type: "N",
  //         osm_id: 5073776567,
  //         osm_key: "railway",
  //         osm_value: "station",
  //         type: "house",
  //         housenumber: "225",
  //         name: "Chicago Union Station",
  //         street: "South Canal Street",
  //         locality: "West Loop Gate",
  //         district: "Near West Side",
  //         city: "Chicago",
  //         county: "Cook County",
  //         state: "Illinois",
  //         country: "United States",
  //         postcode: "60606",
  //         countrycode: "US",
  //       },
  //       geometry: {
  //         type: "Point",
  //         coordinates: [-87.6390928, 41.8786411],
  //       },
  //     },
  //     {
  //       type: "Feature",
  //       properties: {
  //         osm_type: "W",
  //         osm_id: 1392247399,
  //         osm_key: "landuse",
  //         osm_value: "construction",
  //         type: "other",
  //         name: "Chicago Fire Stadium",
  //         locality: "South Loop",
  //         district: "Near South Side",
  //         city: "Chicago",
  //         county: "Cook County",
  //         state: "Illinois",
  //         country: "United States",
  //         countrycode: "US",
  //         extent: [-87.6332834, 41.8661652, -87.6306846, 41.8636894],
  //       },
  //       geometry: {
  //         type: "Point",
  //         coordinates: [-87.631998, 41.8650342],
  //       },
  //     },
  //     {
  //       type: "Feature",
  //       properties: {
  //         osm_type: "W",
  //         osm_id: 210270507,
  //         osm_key: "office",
  //         osm_value: "company",
  //         type: "house",
  //         housenumber: "567",
  //         name: "Chicago Transit Authority Headquarters",
  //         street: "West Lake Street",
  //         locality: "Fulton River District",
  //         district: "Near West Side",
  //         city: "Chicago",
  //         county: "Cook County",
  //         state: "Illinois",
  //         country: "United States",
  //         postcode: "60661",
  //         countrycode: "US",
  //         extent: [-87.6426164, 41.8856106, -87.6420729, 41.8849598],
  //       },
  //       geometry: {
  //         type: "Point",
  //         coordinates: [-87.6423447, 41.8852852],
  //       },
  //     },
  //     {
  //       type: "Feature",
  //       properties: {
  //         osm_type: "W",
  //         osm_id: 203442440,
  //         osm_key: "historic",
  //         osm_value: "building",
  //         type: "house",
  //         housenumber: "210",
  //         name: "Chicago Union Station",
  //         street: "South Canal Street",
  //         locality: "West Loop Gate",
  //         district: "Near West Side",
  //         city: "Chicago",
  //         county: "Cook County",
  //         state: "Illinois",
  //         country: "United States",
  //         postcode: "60606",
  //         countrycode: "US",
  //         extent: [-87.6409806, 41.8791951, -87.6398307, 41.8781389],
  //       },
  //       geometry: {
  //         type: "Point",
  //         coordinates: [-87.6404084, 41.878701],
  //       },
  //     },
  //     {
  //       type: "Feature",
  //       properties: {
  //         osm_type: "R",
  //         osm_id: 17896207,
  //         osm_key: "aeroway",
  //         osm_value: "aerodrome",
  //         type: "house",
  //         housenumber: "5700",
  //         name: "Chicago Midway International Airport",
  //         street: "South Cicero Avenue",
  //         district: "Garfield Ridge",
  //         city: "Lake Township",
  //         county: "Cook County",
  //         state: "Illinois",
  //         country: "United States",
  //         postcode: "60638",
  //         countrycode: "US",
  //         extent: [-87.76686, 41.7952482, -87.7377295, 41.7772284],
  //       },
  //       geometry: {
  //         type: "Point",
  //         coordinates: [-87.7517243, 41.7855142],
  //       },
  //     },
  //   ],
  // };

  if (data.features) {
    const mappedData = data.features.map((f) => {
      const texts: string[] = [];
      console.log(f.properties);

      for (const key of [
        "name",
        "housenumber",
        "street",
        "district",
        "city",
        "state",
        "countrycode",
      ]) {
        if (key in f.properties) {
          texts.push(f.properties[key as keyof typeof f.properties] as string);
        }
      }

      return {
        lat: f.geometry.coordinates[1],
        lng: f.geometry.coordinates[0],
        text: texts.join(", "),
        // type: f.properties.type,
        osm_id: f.properties.osm_id,
      };
    });

    return mappedData;
  }

  return [];
}
